# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MatchingPlugin
                                 A QGIS plugin
 This plugin allows you to create matching links (pairings) between two layers, and it can also, if you wish, produce evolution data on the building.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-02
        copyright            : (C) 2023 by Mouhamadou Ndim (IGN, ENSG, LASTIG)
        email                : mouhamadou.ndim@ign.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MatchingPlugin class from file MatchingPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .matching_plugin import MatchingPlugin
    return MatchingPlugin(iface)
