# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matching_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatchingPluginDialogBase(object):
    def setupUi(self, MatchingPluginDialogBase):
        MatchingPluginDialogBase.setObjectName("MatchingPluginDialogBase")
        MatchingPluginDialogBase.resize(472, 441)
        self.button_box = QtWidgets.QDialogButtonBox(MatchingPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(130, 400, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushButton = QtWidgets.QPushButton(MatchingPluginDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(220, 280, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MatchingPluginDialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 280, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.mQgsFileWidget = gui.QgsFileWidget(MatchingPluginDialogBase)
        self.mQgsFileWidget.setGeometry(QtCore.QRect(320, 40, 90, 27))
        self.mQgsFileWidget.setObjectName("mQgsFileWidget")
        self.mFieldComboBox = gui.QgsFieldComboBox(MatchingPluginDialogBase)
        self.mFieldComboBox.setGeometry(QtCore.QRect(10, 40, 221, 27))
        self.mFieldComboBox.setObjectName("mFieldComboBox")

        self.retranslateUi(MatchingPluginDialogBase)
        self.button_box.accepted.connect(MatchingPluginDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(MatchingPluginDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MatchingPluginDialogBase)

    def retranslateUi(self, MatchingPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MatchingPluginDialogBase.setWindowTitle(_translate("MatchingPluginDialogBase", "Matching Plugin"))
        self.pushButton.setText(_translate("MatchingPluginDialogBase", "Exécuter"))
        self.pushButton_2.setText(_translate("MatchingPluginDialogBase", "Fermer"))
from qgis import gui


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MatchingPluginDialogBase = QtWidgets.QDialog()
    ui = Ui_MatchingPluginDialogBase()
    ui.setupUi(MatchingPluginDialogBase)
    MatchingPluginDialogBase.show()
    sys.exit(app.exec_())
